linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - gomnd
    - funlen

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - gocognit
        - cyclop
        - wrapcheck
        - maintidx
        - dogsled
        - contextcheck
        - dupword
        - dupl
        - funlen

linters-settings:
  varnamelen:
    ignore-names:
      - tt
    ignore-decls:
      - i int
      - a ...any
      - err error
      - ok bool
      - id string
      - w http.ResponseWriter
      - rt http.RoundTripper
      - r *http.Request
      - l net.Listener
      - t reflect.Type
      - wg sync.WaitGroup
      - mu sync.Mutex
      - ch chan<- prometheus.Metric
  lll:
    line-length: 160
